# Generated by Django 5.2.5 on 2025-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Argent comptant'), ('debit', 'Carte de débit'), ('credit', 'Carte de crédit'), ('cheque', 'Chèque'), ('transfer', 'Virement bancaire'), ('other', 'Autre')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
    ]
