# Generated by Django 5.2.5 on 2025-08-14 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0002_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_year_end_day',
            field=models.IntegerField(default=31, help_text='Jour où se termine votre année fiscale (défaut: 31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name="Jour de fin d'année fiscale"),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_year_end_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12, help_text='Mois où se termine votre année fiscale (défaut: décembre)', verbose_name="Mois de fin d'année fiscale"),
        ),
    ]
