# Generated by Django 5.2.5 on 2025-08-14 10:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0003_add_fiscal_year_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='archived_fiscal_year',
            field=models.IntegerField(blank=True, help_text="Si défini, cette dépense fait partie d'une année fiscale archivée", null=True, verbose_name='Année fiscale archivée'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='archived_fiscal_year',
            field=models.IntegerField(blank=True, help_text="Si défini, cette facture fait partie d'une année fiscale archivée", null=True, verbose_name='Année fiscale archivée'),
        ),
        migrations.CreateModel(
            name='FiscalYearArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='Année de fin de la période fiscale (ex: 2024 pour la période 2023-2024)', verbose_name='Année fiscale')),
                ('archive_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'archivage")),
                ('total_invoices', models.IntegerField(default=0, verbose_name='Nombre de factures')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Chiffre d'affaires total")),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total des dépenses')),
                ('total_gst_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TPS perçue')),
                ('total_qst_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TVQ perçue')),
                ('total_gst_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TPS payée')),
                ('total_qst_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TVQ payée')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_locked', models.BooleanField(default=False, help_text="Une fois verrouillé, l'archive ne peut plus être modifiée", verbose_name='Verrouillé')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Archivé par')),
            ],
            options={
                'verbose_name': "Archive d'année fiscale",
                'verbose_name_plural': "Archives d'années fiscales",
                'ordering': ['-fiscal_year'],
                'unique_together': {('fiscal_year',)},
            },
        ),
    ]
