# Generated by Django 5.2.5 on 2025-08-15 09:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0005_add_advanced_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('materials', 'Matériaux'), ('tools', 'Outils'), ('inventory', 'Inventaire/Marchandises'), ('rent', 'Loyer'), ('utilities', 'Services publics'), ('insurance', 'Assurance'), ('marketing', 'Marketing'), ('fuel', 'Carburant'), ('maintenance', 'Entretien'), ('office', 'Fournitures de bureau'), ('professional', 'Services professionnels'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('materials', 'Matériaux'), ('tools', 'Outils'), ('inventory', 'Inventaire/Marchandises'), ('rent', 'Loyer'), ('utilities', 'Services publics'), ('insurance', 'Assurance'), ('marketing', 'Marketing'), ('fuel', 'Carburant'), ('maintenance', 'Entretien'), ('office', 'Fournitures de bureau'), ('professional', 'Services professionnels'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de bon de réception')),
                ('receipt_date', models.DateField(verbose_name='Date de réception')),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de facture fournisseur')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sous-total')),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TPS')),
                ('qst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TVQ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant total')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('received', 'Reçu'), ('processed', 'Traité'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipt', to='garage_app.expense', verbose_name='Dépense associée')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_receipts', to='garage_app.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de réception',
                'verbose_name_plural': 'Bons de réception',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité reçue')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix d'achat unitaire")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage_app.inventoryitem', verbose_name='Article')),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='garage_app.stockreceipt', verbose_name='Bon de réception')),
            ],
            options={
                'verbose_name': 'Élément de réception',
                'verbose_name_plural': 'Éléments de réception',
                'unique_together': {('stock_receipt', 'inventory_item')},
            },
        ),
    ]
