# Generated by Django 5.2.5 on 2025-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0006_add_stock_receipt_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('package', 'Forfaits Signature'), ('tinting', 'Vitres teintées'), ('ppf', 'Protection pare-pierre (PPF)'), ('wrapping', 'Wrapping / Personnalisation'), ('ceramic', 'Protection céramique'), ('hydrophobic', 'Protection hydrophobe'), ('detailing', 'Esthétique & Correction de peinture'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
    ]
