# Generated by Django 5.2.5 on 2025-08-16 09:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0007_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du rabais')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='Type de rabais')),
                ('value', models.DecimalField(decimal_places=2, help_text='Pourcentage (ex: 10.00 pour 10%) ou montant fixe (ex: 50.00 pour 50$)', max_digits=10, verbose_name='Valeur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rabais',
                'verbose_name_plural': 'Rabais',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant du rabais'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_description',
            field=models.CharField(blank=True, help_text='Description personnalisée du rabais (optionnel)', max_length=200, null=True, verbose_name='Description du rabais'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_discount',
            field=models.ForeignKey(blank=True, help_text='Rabais automatiquement appliqué aux factures de ce client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage_app.discount', verbose_name='Rabais par défaut'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage_app.discount', verbose_name='Rabais appliqué'),
        ),
    ]
