# Generated by Django 5.2.5 on 2025-08-16 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0008_add_discount_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_description',
        ),
        migrations.AddField(
            model_name='client',
            name='default_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rabais automatiquement appliqué aux factures de ce client (0-100%)', max_digits=5, verbose_name='Pourcentage de rabais par défaut (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Pourcentage de rabais (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_dealer_discount',
            field=models.BooleanField(default=False, verbose_name='Rabais concessionnaire (30%)'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
