# Generated by Django 5.2.5 on 2025-08-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0009_simplify_discount_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vin',
        ),
    ]
