# Generated by Django 5.2.5 on 2025-08-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0010_remove_vin_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
    ]
