# Generated by Django 5.2.5 on 2025-08-16 10:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0011_remove_due_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix'),
            preserve_default=False,
        ),
    ]
