# Generated by Django 5.2.5 on 2025-08-16 11:14

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0012_simplify_invoice_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de soumission')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date de création')),
                ('valid_until', models.DateField(verbose_name="Valide jusqu'au")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('expired', 'Expirée'), ('converted', 'Convertie en facture')], default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sous-total')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Pourcentage de rabais')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant du rabais')),
                ('is_dealer_discount', models.BooleanField(default=False, verbose_name='Rabais concessionnaire')),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant TPS')),
                ('qst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant TVQ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('terms_conditions', models.TextField(blank=True, null=True, verbose_name='Conditions générales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='garage_app.client', verbose_name='Client')),
                ('converted_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='garage_app.invoice', verbose_name='Facture convertie')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='garage_app.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-date', '-quote_number'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('service', 'Service'), ('inventory', "Article d'inventaire")], default='service', max_length=20, verbose_name="Type d'élément")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description personnalisée')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage_app.inventoryitem', verbose_name="Article d'inventaire")),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='garage_app.quote', verbose_name='Soumission')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage_app.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Élément de soumission',
                'verbose_name_plural': 'Éléments de soumission',
                'ordering': ['id'],
            },
        ),
    ]
