# Generated by Django 5.2.5 on 2025-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0013_quote_quoteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
    ]
