# Generated by Django 5.2.5 on 2025-08-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0014_remove_quoteitem_quantity_alter_quoteitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.IntegerField(default=0, verbose_name='Niveau de réapprovisionnement'),
        ),
    ]
