# Generated by Django 5.2.5 on 2025-08-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0015_add_reorder_level_to_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('reorder', 'Réapprovisionnement'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture de stock')], default='reorder', max_length=20, verbose_name="Type d'alerte")),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Prise en compte'), ('resolved', 'Résolue'), ('dismissed', 'Ignorée')], default='active', max_length=20, verbose_name='Statut')),
                ('alert_date', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'alerte")),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de prise en compte')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('quantity_at_alert', models.IntegerField(verbose_name="Quantité au moment de l'alerte")),
                ('threshold_level', models.IntegerField(verbose_name='Seuil déclenché')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='Action entreprise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='garage_app.inventoryitem', verbose_name="Article d'inventaire")),
            ],
            options={
                'verbose_name': 'Alerte de stock',
                'verbose_name_plural': 'Alertes de stock',
                'ordering': ['-alert_date'],
                'unique_together': {('inventory_item', 'alert_type', 'status')},
            },
        ),
    ]
