# Generated by Django 5.2.5 on 2025-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0017_add_vehicle_type_and_service_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='quality_tier',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('ceramic', 'Céramique'), ('premium', 'Premium'), ('ultra', 'Ultra Premium')], help_text='Niveau de qualité du matériau pour la tarification dynamique', max_length=20, null=True, verbose_name='Niveau de qualité'),
        ),
    ]
