# Generated by Django 5.2.5 on 2025-08-17 15:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0018_add_quality_tier_to_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='minimum_stock_level',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Niveau de stock minimum'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Niveau de réapprovisionnement'),
        ),
    ]
