# Generated by Django 5.2.5 on 2025-08-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0019_convert_inventory_quantities_to_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('conception', 'Conception Graphique'), ('installation', 'Installation'), ('echenillage', 'Échenillage'), ('preparation', 'Préparation'), ('finition', 'Finition')], max_length=20, unique=True, verbose_name='Type de tâche')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Votre taux facturable par heure en CAD', max_digits=8, verbose_name='Taux horaire')),
                ('description', models.TextField(blank=True, help_text='Description de ce type de tâche', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Taux actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taux horaire',
                'verbose_name_plural': 'Taux horaires',
                'ordering': ['task_type'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Vinyle Coulé 3M IJ180Cv3, Lamination Lustrée', max_length=100, verbose_name='Nom du matériau')),
                ('type', models.CharField(choices=[('vinyle', 'Vinyle'), ('lamination', 'Lamination'), ('encre', 'Encre'), ('autre', 'Autre')], max_length=20, verbose_name='Type de matériau')),
                ('cost_per_sqm', models.DecimalField(decimal_places=2, help_text='Coût par mètre carré en CAD', max_digits=8, verbose_name='Coût par m²')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Fournisseur')),
                ('notes', models.TextField(blank=True, help_text='Informations supplémentaires sur ce matériau', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Matériau actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matériau',
                'verbose_name_plural': 'Matériaux',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OverheadConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Configuration Standard, Configuration Premium', max_length=100, verbose_name='Nom de la configuration')),
                ('hourly_overhead_cost', models.DecimalField(decimal_places=2, help_text='Montant fixe en CAD à ajouter pour chaque heure de travail', max_digits=8, verbose_name='Frais généraux par heure')),
                ('fixed_overhead_cost', models.DecimalField(decimal_places=2, default=0, help_text='Montant fixe en CAD à ajouter à chaque projet', max_digits=8, verbose_name='Frais fixes')),
                ('percentage_overhead', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage du coût total à ajouter comme frais généraux', max_digits=5, verbose_name='Pourcentage de frais généraux')),
                ('is_active', models.BooleanField(default=True, verbose_name='Configuration active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Configuration par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration frais généraux',
                'verbose_name_plural': 'Configurations frais généraux',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='complexity_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicateur de complexité pour le lettrage (ex: Berline=1.0, Sprinter=1.6)', max_digits=4, verbose_name='Multiplicateur de complexité'),
        ),
    ]
