# Generated by Django 5.2.5 on 2025-08-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0020_laborrate_material_overheadconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetteringQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_area', models.DecimalField(decimal_places=2, help_text='Surface totale à couvrir en mètres carrés', max_digits=8, verbose_name='Surface totale (m²)')),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='Pourcentage de perte de matériau', max_digits=5, verbose_name='Taux de perte (%)')),
                ('design_hours', models.DecimalField(decimal_places=2, default=0, help_text='Temps estimé pour la conception graphique', max_digits=6, verbose_name='Heures de conception')),
                ('installation_hours', models.DecimalField(decimal_places=2, help_text="Temps estimé pour l'installation", max_digits=6, verbose_name="Heures d'installation")),
                ('profit_margin', models.DecimalField(decimal_places=2, default=30.0, help_text='Marge bénéficiaire en pourcentage', max_digits=5, verbose_name='Marge bénéficiaire (%)')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, help_text='Coût total des matériaux calculé automatiquement', max_digits=10, verbose_name='Coût matériaux')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text="Coût total de la main-d'œuvre calculé automatiquement", max_digits=10, verbose_name="Coût main-d'œuvre")),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, help_text='Frais généraux calculés automatiquement', max_digits=10, verbose_name='Frais généraux')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Coût total avant marge', max_digits=10, verbose_name='Coût total')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, help_text='Prix final avec marge bénéficiaire', max_digits=10, verbose_name='Prix final')),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires sur ce projet', verbose_name='Notes')),
                ('is_converted_to_quote', models.BooleanField(default=False, help_text='Indique si ce calcul a été converti en soumission officielle', verbose_name='Converti en soumission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage_app.client', verbose_name='Client')),
                ('lamination_material', models.ForeignKey(blank=True, limit_choices_to={'type': 'lamination'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lamination_quotes', to='garage_app.material', verbose_name='Lamination')),
                ('overhead_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage_app.overheadconfiguration', verbose_name='Configuration frais généraux')),
                ('related_quote', models.ForeignKey(blank=True, help_text='Soumission officielle créée à partir de ce calcul', null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage_app.quote', verbose_name='Soumission liée')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage_app.vehicle', verbose_name='Véhicule')),
                ('vinyl_material', models.ForeignKey(limit_choices_to={'type': 'vinyle'}, on_delete=django.db.models.deletion.PROTECT, related_name='vinyl_quotes', to='garage_app.material', verbose_name='Vinyle')),
            ],
            options={
                'verbose_name': 'Calcul de lettrage',
                'verbose_name_plural': 'Calculs de lettrage',
                'ordering': ['-created_at'],
            },
        ),
    ]
