# Generated by Django 5.2.5 on 2025-08-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0021_letteringquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='lettering_details',
            field=models.JSONField(blank=True, help_text='Détails du calcul de lettrage (surface, matériaux, heures, etc.)', null=True, verbose_name='Détails du lettrage'),
        ),
    ]
