# Generated by Django 5.2.5 on 2025-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0022_quoteitem_lettering_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='letteringquote',
            name='final_price_with_taxes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix final incluant toutes les taxes', max_digits=10, verbose_name='Prix final avec taxes'),
        ),
        migrations.AddField(
            model_name='letteringquote',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la TPS (5%)', max_digits=10, verbose_name='Montant TPS'),
        ),
        migrations.AddField(
            model_name='letteringquote',
            name='qst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la TVQ (9.975%)', max_digits=10, verbose_name='Montant TVQ'),
        ),
        migrations.AlterField(
            model_name='letteringquote',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix avec marge bénéficiaire avant taxes', max_digits=10, verbose_name='Prix avant taxes'),
        ),
    ]
