# Generated by Django 5.2.5 on 2025-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0023_letteringquote_final_price_with_taxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('vinyle', 'Vinyle'), ('vinyle_decoupe', 'Vinyle Découpé'), ('lamination', 'Lamination'), ('encre', 'Encre'), ('autre', 'Autre')], max_length=20, verbose_name='Type de matériau'),
        ),
    ]
