# Generated by Django 5.2.5 on 2025-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0024_alter_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='work_type',
            field=models.CharField(choices=[('wrapping', 'Habillage / Wrapping'), ('lettrage_decoupe', 'Lettrage Découpé')], default='wrapping', help_text='Type de travail à effectuer', max_length=20, verbose_name='Type de travail'),
        ),
    ]
