# Generated by Django 5.2.5 on 2025-08-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0025_quote_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='work_type',
        ),
    ]
